kockatykalendar/data

example.yml, schemas/event.schema.json
=> Short info

example.yml, schemas/event.schema.json
=> Override color

data/2020_21/02_october/iks.yml, data/2020_21/03_november/4_iks.yml, data/2020_21/04_december/iks.yml, data/2020_21/06_february/6_iks.yml
=> fix iks science

.gitignore, build.py
Aby sme vedeli, aké dáta sú k dispozícií.
=> Generate index.json to show all available school years

data/2020_21/ksp/1_ksp.yml, data/2020_21/ksp/1_ksp_doprogramovanie.yml, data/2020_21/ksp/ksp_sustredko.yml
=> Add 1. kolo KSP

.github/workflows/build_json.yml
Kedze toto potrebuje personal access token a na GH nie je možnosť ich limitovať na konkrétne repozitáre, token patrí @kockatykalendar-ci.
=> Send dispatch event to iCal repository

data/2020_21/ksp/z2_ksp.yml, data/2020_21/ksp/z2_ksp_doprogramovanie.yml
Zasekla sa priprava jednej ulohy
=> ksp: r38/z2: Postpone deadlines by a week

.github/workflows/pr_check.yml
Po vytvorení pull requestu by sa mali skontrolovať dáta, nech nemergujeme niečo zlé.
=> Add data check for PRs

data/2020_21/08_april/mat_naboj.yml
Medzinarodne sme sa rozhodli naboj posunut
=> naboj zmena terminu

data/2020_21/05_january/malynar.yml, data/2020_21/05_january/susi.yml, data/2020_21/06_february/matik.yml, data/2020_21/06_february/pikofyz.yml, data/2020_21/06_february/pikomat_mladsi.yml, data/2020_21/06_february/pikomat_starsi.yml
=> fix canceled to cancelled

data/2020_21/08_april/kockac.yml, data/2020_21/08_april/kockac2.yml, data/2020_21/08_april/pikofyz.yml, data/2020_21/08_april/pikomat_mladsi.yml, data/2020_21/08_april/pikomat_starsi.yml
sorry @ano95 som zabudol zrušiť kockáče
=> 2021 pmat sustredka jar

data/2020_21/07_march/pmat_online.yml
Presne pre toto som chcel aby to kontrolovalo organizátorov...
=> 2021 pmat online aktivita

data/2020_21/09_may/mamut.yml, data/2020_21/12_august/letny_strom.yml, data/2020_21/12_august/tmm.yml
Pridané:
- Letné sústredenie STROMu
- TMM
Upravené:
- Mamut
=> March update

data/2020_21/09_may/testovanie_5.yml
https://www.minedu.sk/rozhodnutie-ministra-zo-4-1-2021/
=> Zrušené testovanie 5

data/2021_22/sutaze/jesenny_gvoboj.yml
Rád by som pri tom mal keď už viac údajov, kde sa prihlásiť, ... Ale nenašiel som.
=> add jesenny GVOBOJ

data/2021_22/sutaze/miniprog.yml
- miniprog22: add home round
- miniprog22: edit title
=> Miniprog 2022 home round

utils/add2021_22, utils/create_trojsten_seminar.py
- add-utils: add utility to create trojsten seminar
- add-utils: add 2021/22 trojsten helper
=> add Trojsten utils

data/2021_22/seminare/strom/Zsustredenie.yaml, data/2021_22/seminare/strom/ZsustredenieMalynar.yaml, data/2021_22/seminare/strom/ZsustredenieMatik.yaml, data/2021_22/seminare/strom/rba.yml, data/2021_22/seminare/strom/tmm.yml
Jarný update STROMáckych akcií:
- Posun zimných sústredení
- TMM
- RBA
=> Update jarnych STROMackych akcii

data/2022_23/seminare/P-MAT/ZsustredeniePMS.yaml
=> Fix datumu

data/2024_25/seminare/trojsten/SUSI/1_1_after1.yml, data/2024_25/seminare/trojsten/SUSI/1_1_after2.yml, data/2024_25/seminare/trojsten/SUSI/1_1_start.yml, data/2024_25/seminare/trojsten/SUSI/1_2_after1.yml, data/2024_25/seminare/trojsten/SUSI/1_2_after2.yml, data/2024_25/seminare/trojsten/SUSI/1_2_start.yml, data/2024_25/seminare/trojsten/SUSI/1_Outdoor_after1.yml, data/2024_25/seminare/trojsten/SUSI/1_Outdoor_after2.yml, data/2024_25/seminare/trojsten/SUSI/1_Outdoor_start.yml, data/2024_25/seminare/trojsten/SUSI/2_1_after1.yml, data/2024_25/seminare/trojsten/SUSI/2_1_after2.yml, data/2024_25/seminare/trojsten/SUSI/2_1_start.yml, data/2024_25/seminare/trojsten/SUSI/2_2_after1.yml, data/2024_25/seminare/trojsten/SUSI/2_2_after2.yml, data/2024_25/seminare/trojsten/SUSI/2_2_start.yml, data/2024_25/seminare/trojsten/SUSI/2_Outdoor_after1.yml, data/2024_25/seminare/trojsten/SUSI/2_Outdoor_after2.yml, data/2024_25/seminare/trojsten/SUSI/2_Outdoor_start.yml, utils/create_trojsten_seminar.py
- **2024-25-trojsten-riesky-kola: add all dates**
- **2024-25-susi-fix: fix secondary dates**
=> 2024 25 susi fix

data/2024_25/seminare/P-MAT/KVjar.yaml, data/2024_25/seminare/P-MAT/KVjesen.yaml, data/2024_25/seminare/P-MAT/L1seriaPF.yaml, data/2024_25/seminare/P-MAT/L1seriaPM.yaml, data/2024_25/seminare/P-MAT/L2seriaPF.yaml, data/2024_25/seminare/P-MAT/L2seriaPM.yaml, data/2024_25/seminare/P-MAT/L3seriaPF.yaml, data/2024_25/seminare/P-MAT/L3seriaPM.yaml, data/2024_25/seminare/P-MAT/LsustredeniePF.yaml, data/2024_25/seminare/P-MAT/LsustredeniePMM.yaml, data/2024_25/seminare/P-MAT/LsustredeniePMS.yaml, data/2024_25/seminare/P-MAT/Z1seriaPM.yaml, data/2024_25/seminare/P-MAT/Z1seriaTB.yaml, data/2024_25/seminare/P-MAT/Z2seriaPF.yaml, data/2024_25/seminare/P-MAT/Z2seriaPM.yaml, data/2024_25/seminare/P-MAT/Z2seriaTB.yaml, data/2024_25/seminare/P-MAT/Z3seriaPF.yaml, data/2024_25/seminare/P-MAT/Z3seriaPM.yaml, data/2024_25/seminare/P-MAT/ZsustredeniePF.yaml, data/2024_25/seminare/P-MAT/ZsustredeniePMM.yaml, data/2024_25/seminare/P-MAT/ZsustredeniePMS.yaml
Termíny sérii a sústredení na najbližší rok
=> Pmat terminy

build.py, data/2023_24/seminare/Riesky/Rieskysusl.yml, data/2023_24/seminare/Riesky/Rieskysusz.yml, data/2023_24/seminare/Sezam/SezamMaK1.yml, data/2023_24/seminare/Sezam/SezamMaK2.yml, data/2023_24/seminare/Sezam/SezamMaK3.yml, data/2023_24/seminare/Sezam/SezamMaK4.yml, data/2023_24/seminare/Sezam/SezamMaK5.yml, data/2023_24/seminare/Sezam/Sezamkostret.yml, data/2023_24/seminare/Sezam/Sezamkosusl.yml, data/2023_24/seminare/Sezam/Sezamsusz.yml, data/2023_24/seminare/Sezam/Sezamtabor.yml, data/2024_25/seminare/riesky/Rieskysusl.yml, data/2024_25/seminare/riesky/Rieskysusz.yml, data/2024_25/seminare/riesky/tabor.yml, data/2024_25/seminare/trojsten/FKS/FKS_leto_sustredenie.yml, data/2024_25/seminare/trojsten/FKS/FKS_zima_sustredenie.yml, data/2025_26/seminare/Riesky/Rieskysusl.yml, data/2025_26/seminare/Riesky/Rieskysusz.yml, schemas/event.schema.json
First, https://github.com/kockatykalendar/frontend/pull/142 needs to be merged for frontend to adapt to changes properly.
=> Change "places" to be optional, add warning into schema when not set
